In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re # Regular Expression
import string # contains all string value
from sklearn.model_selection import train_test_split # Use the train the dataset
from sklearn.metrics import accuracy_score # Check the accuracy values
from sklearn.metrics import classification_report
from sklearn.linear_model import LogisticRegression # Binary values 0 and 1
from sklearn.feature_extraction.text import TfidfVectorizer # converts num to text tfidf - Term Frequency -Inverse Documents Frequency
from sklearn.ensemble import RandomForestClassifier # Help to identify the different tree (randomforest is a type of decisiontree but class.. model)
from sklearn.naive_bayes import MultinomialNB # text classification

In [2]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'https?://\S+', '', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', ' ', text)
    text = re.sub(r'\w*\d\w*', '', text)
    return text

In [3]:
df_fake=pd.read_csv(r"C:\CODE\Project\News Detection\Fake.csv\Fake.csv")
df_true=pd.read_csv(r"C:\CODE\Project\News Detection\True.csv\True.csv")

In [4]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [5]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [6]:
df_fake.shape , df_true.shape

((23481, 4), (21417, 4))

In [7]:
df_fake['label']=0
df_true['label']=1

In [8]:
df_true.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [9]:
df_fake.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [10]:
df=pd.concat ([df_fake , df_true])

In [11]:
df.head()

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0

In [12]:
df.shape

(44898, 5)

In [13]:
df=df.sample(frac=1 , random_state=52)

In [14]:
df.head()

,title,text,subject,date,label
15319,U.S. military joins Brazil army exercises in A...,"TABATINGA, Brazil (Reuters) - U.S. military pe...",worldnews,"November 8, 2017",1
6705,Factbox: Trump fills top jobs for his administ...,(Reuters) - U.S. President-elect Donald Trump ...,politicsNews,"December 13, 2016",1
19459,Germany will strive to save Iran nuclear deal:...,NEW YORK/BERLIN (Reuters) - Germany will do al...,worldnews,"September 21, 2017",1
16295,TRUMP MEETS WITH TECH GIANTS: “Everybody in th...,Trump to tech leaders: You re doing well righ...,Government News,"Dec 14, 2016",0
11358,Chess federation says Israel excluded from Sau...,ATHENS (Reuters) - Israeli players have been d...,worldnews,"December 24, 2017",1

In [15]:
x=df['text']
y=df['label']

In [16]:
x.head()

15319    TABATINGA, Brazil (Reuters) - U.S. military pe...
6705     (Reuters) - U.S. President-elect Donald Trump ...
19459    NEW YORK/BERLIN (Reuters) - Germany will do al...
16295    Trump to tech leaders:  You re doing well righ...
11358    ATHENS (Reuters) - Israeli players have been d...
Name: text, dtype: object

In [17]:
y.head()

15319    1
6705     1
19459    1
16295    0
11358    1
Name: label, dtype: int64

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [19]:
x_train

23031    21st Century Wire says Tuesday, President Dona...
14386    ISTANBUL (Reuters) - Turkish authorities on Mo...
10451    (Reuters) - Near the end of his eight years as...
15020    AH LEI THAN KYAW, Myanmar (Reuters) - Some 1,0...
942      WASHINGTON (Reuters) - Senate Republican leade...
                               ...
3944     The following statements were posted to the ve...
10429    TALLAHASSEE, Fla. (Reuters) - Florida legislat...
20905    According to insider, and author Edward Klein,...
21249    This is a MUST watch from start to finish. The...
6300     One of the tenets of Christianity is  Thou sha...
Name: text, Length: 35918, dtype: object

In [20]:
x_test

11827    MANILA (Reuters) - Philippine President Rodrig...
15757    LONDON (Reuters) - Israeli Prime Minister Benj...
2060     Astrophysicist Neil deGrasse Tyson is NOT a fa...
19485    (Reuters) - Hurricane Maria is continuing to l...
19283    Immediately after this happened, Charles Kraut...
                               ...
19954    CONAKRY (Reuters) - Unrest over wages and elec...
15990    WASHINGTON (Reuters) - The World Bank on Tuesd...
11956    SYDNEY (Reuters) - Australian Prime Minister M...
86       Alabama Senate Candidate Roy Moore (R- Of Cour...
12681    WASHINGTON (Reuters) - The U.S. envoy for Nort...
Name: text, Length: 8980, dtype: object

In [21]:
vectorizer=TfidfVectorizer(stop_words='english',max_df=0.7)

In [22]:
x_train=vectorizer.fit_transform(x_train)

In [23]:
x_test=vectorizer.transform(x_test)

In [24]:
model=LogisticRegression(max_iter=1000)

In [25]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [26]:
y_pred=model.predict(x_test)

In [27]:
y_pred

array([1, 1, 0, ..., 1, 0, 1], shape=(8980,))

In [28]:
accuracy_score(y_test,y_pred)

0.9883073496659243

In [51]:
news=input("Enter a Detection news")

Enter a Detection news WASHINGTON (Reuters) - The head of a conservative Republican faction in the U.S. Congress, who voted this month for a huge expansion of the national debt to pay for tax cuts, called himself a â€œfiscal conservativeâ€ on Sunday and urged

In [52]:
def predict_news(news):
    news_vector=vectorizer.transform([news])
    prediction=model.predict(news_vector)

    if prediction == 1 :
        print("True",accuracy_score)
    else :
        print('False',accuracy_score)

    return prediction 
result=predict_news(news)
print(result)

True <function accuracy_score at 0x000001E7E8630720>
[1]